pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('front'){
                    sh '''
                    pwd
                    echo 'prepare'
                    npm install -g yarn

                    echo 'yarn install'
                    yarn install
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Build') {
            steps {
                dir('front') {
                    sh '''
                    echo 'yarn build'
                    yarn build
                    '''
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('front'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-react:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('front'){
                    sh '''
                    echo 'Deploy'

                    docker run -d -p 3000:3000 --name react docker-react:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}