pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('back/B306'){
                    sh '''
                    pwd
                    echo 'springboot build'
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Dockerimage build') {
            steps {
                dir('back/B306'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot-bfo:0.0.1 .
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('back/B306'){
                    sh '''
                    echo 'Deploy'

                    docker stop springboot_bfo
                    docker rm springboot_bfo

                    docker run -d -p 8083:8080 --name springboot_bfo docker-springboot-bfo:0.0.1
                    '''
                }
            }
            post {
                success {
                    sh 'echo "Successfully "'
                }
                failure {
                    sh 'echo "Fail"'
                }
            }
        }
    }
}